### ISSUE TITLE
Readme not descriptive enough?

### ISSUE THREAD

**Issue by databoose** [meefik/avd-root#2]
The very first step says :

> Find out the name of AVD:
> 
> emulator -list-avds

What emulator command? From what program? In what context? Because i have android studio installed alongside the AVD and this command does not exist at all on my system, could you provide more information about what this "emulator" command comes from and how to install the program responsible for it?

**Comment by chikazin** [comment]
`cd` to the `/androidsdk/tools` directory of your android sdk path, then you can access the `emulator.exe` file with parameters  by the `emulator -list-avds` command which list the devices' name of your AVDs.
